name: Main Workflow


on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: npm setup
      run: npm install
    
    - name: make soft link
      run: ln -s todo.sh todo
    
    - name: Run Automated Tests
      run: npm test